Configuration: Release
NugetPackages:
  - 
    Name: Thuria.Zitidar.Core
    Version: 2.1.1
  - 
    Name: Thuria.Zitidar.Caching.Abstractions
    Version: 2.1.1
  - 
    Name: Thuria.Zitidar.Caching
    Version: 2.1.1
  - 
    Name: Thuria.Zitidar.Extensions
    Version: 1.12.1
  - 
    Name: Thuria.Zitidar.WebApi.Abstractions
    Version: 1.1.1
  - 
    Name: Thuria.Zitidar.WebApi
    Version: 1.1.1
