Configuration: Release
NugetPackages:
  - 
    Name: Thuria.Zitidar.Core
    Version: 2.0.0
  - 
    Name: Thuria.Zitidar.Caching.Abstractions
    Version: 2.0.4
  - 
    Name: Thuria.Zitidar.Caching
    Version: 2.0.4
  - 
    Name: Thuria.Zitidar.Extensions
    Version: 1.11.2
  - 
    Name: Thuria.Zitidar.WebApi.Abstractions
    Version: 1.0.1
  - 
    Name: Thuria.Zitidar.WebApi
    Version: 1.0.1
