VERSION: 1.6.0
CONFIGURATION: Release
NUGETPACKAGES:
  - Core:
    Name: Zitidar.Core
    Version: 1.8.0
    Location: src/Thuria.Zitidar.Core
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net8
      - netstandard2.0
      - netcoreapp3.1
      - net6
      - net7
  - Extensions:
    Name: Zitidar.Extensions
    Version: 1.8.0
    Location: src/Thuria.Zitidar.Extensions
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net8
      - netstandard2.0
      - netcoreapp3.1
      - net6
      - net7
  - Caching:
    Name: Zitidar.Caching
    Version: 1.8.0
    Location: src/Thuria.Zitidar.Caching
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net8
      - netstandard2.0
      - netcoreapp3.1
      - net6
      - net7
  - Logging:
    Name: Zitidar.Logging
    Version: 1.9.0
    Location: src/Thuria.Zitidar.Logging
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net8
      - netstandard2.0
      - netcoreapp3.1
      - net6
      - net7
  - Settings:
    Name: Zitidar.Settings
    Version: 1.8.0
    Location: src/Thuria.Zitidar.Settings
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net8
      - netstandard2.0
      - netcoreapp3.1
      - net6
      - net7
