VERSION: 1.0.0
CONFIGURATION: Release
NUGETPACKAGES:
  - Core:
    Name: Zitidar.Core
    Version: 1.4.0
    Location: src/Thuria.Zitidar.Core
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - netstandard2.0
      - netcoreapp3.0
  - Extensions:
    Name: Zitidar.Extensions
    Version: 1.3.0
    Location: src/Thuria.Zitidar.Extensions
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - netstandard2.0
      - netcoreapp3.0
  - Caching:
    Name: Zitidar.Caching
    Version: 1.1.0
    Location: src/Thuria.Zitidar.Caching
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - netstandard2.0
      - netcoreapp3.0
  - Lamar:
    Name: Zitidar.Lamar
    Version: 0.0.2
    Location: src/Thuria.Zitidar.Lamar
    IsBeta: true
  - Structuremap:
    Name: Zitidar.Structuremap
    Version: 1.1.0
    Location: src/Thuria.Zitidar.Structuremap
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - netstandard2.0
      - netcoreapp3.0
  - Settings:
    Name: Zitidar.Settings
    Version: 1.0.0
    Location: src/Thuria.Zitidar.Settings
    IsBeta: false
  - Akka:
    Name: Zitidar.Akka
    Version: 0.0.18
    Location: src/Thuria.Zitidar.Akka
    IsBeta: true  
  - Logging:
    Name: Zitidar.Logging
    Version: 1.0.0
    Location: src/Thuria.Zitidar.Logging
    IsBeta: false
  - Serialization:
    Name: Zitidar.Serialization
    Version: 1.0.0
    Location: src/Thuria.Zitidar.Serialization
    IsBeta: false
