VERSION: 1.10.0
CONFIGURATION: Release
NUGETPACKAGES:
  - Core:
    Name: Zitidar.Core
    Version: 1.10.1
    Location: src/Thuria.Zitidar.Core
    IsBeta: false
    Frameworks:
      - net472
      - net8
      - netstandard2.0
      - net6
      - net7
      - net8
  - Extensions:
    Name: Zitidar.Extensions
    Version: 1.10.1
    Location: src/Thuria.Zitidar.Extensions
    IsBeta: false
    Frameworks:
      - net472
      - net8
      - netstandard2.0
      - net6
      - net7
      - net8
  - Caching:
    Name: Zitidar.Caching
    Version: 1.10.1
    Location: src/Thuria.Zitidar.Caching
    IsBeta: false
    Frameworks:
      - net472
      - net8
      - netstandard2.0
      - net6
      - net7
      - net8
  - Logging:
    Name: Zitidar.Logging
    Version: 1.10.1
    Location: src/Thuria.Zitidar.Logging
    IsBeta: false
    Frameworks:
      - net472
      - net8
      - netstandard2.0
      - net6
      - net7
      - net8
  - Settings:
    Name: Zitidar.Settings
    Version: 1.10.1
    Location: src/Thuria.Zitidar.Settings
    IsBeta: false
    Frameworks:
      - net472
      - net8
      - netstandard2.0
      - net6
      - net7
      - net8
