Configuration: Release
NugetPackages:
  - 
    Name: Thuria.Zitidar.Caching.Abstractions
    Version: 2.0.2
  - 
    Name: Thuria.Zitidar.Caching
    Version: 2.0.2
  - 
    Name: Thuria.Zitidar.Extensions
    Version: 2.0.2