VERSION: 0.1.0
CONFIGURATION: Release
NUGETPACKAGES:
  - Core:
    Name: Zitidar.Core
    Version: 0.1.0
    Location: src/Thuria.Zitidar.Core
    IsBeta: false
  - Extensions:
    Name: Zitidar.Extensions
    Version: 0.1.0
    Location: src/Thuria.Zitidar.Extensions
    IsBeta: false
  - Lamar:
    Name: Zitidar.Lamar
    Version: 0.0.1
    Location: src/Thuria.Zitidar.Lamar
    IsBeta: true
  - Structuremap:
    Name: Zitidar.Structuremap
    Version: 0.0.14
    Location: src/Thuria.Zitidar.Structuremap
    IsBeta: true
  - Settings:
    Name: Zitidar.Settings
    Version: 0.1.0
    Location: src/Thuria.Zitidar.Settings
    IsBeta: false
  - Akka:
    Name: Zitidar.Akka
    Version: 0.0.15
    Location: src/Thuria.Zitidar.Akka
    IsBeta: true  
  - Logging:
    Name: Zitidar.Logging
    Version: 0.0.3
    Location: src/Thuria.Zitidar.Logging
    IsBeta: true
  - Nancy:
    Name: Zitidar.Nancy
    Version: 0.0.6
    Location: src/Thuria.Zitidar.Nancy
    IsBeta: true
  - Serialization:
    Name: Zitidar.Serialization
    Version: 0.1.0
    Location: src/Thuria.Zitidar.Serialization
    IsBeta: false
  - NancySerialization:
    Name: Zitidar.Serialization.Nancy
    Version: 0.1.0
    Location: src/Thuria.Zitidar.Serialization.Nancy
    IsBeta: false
